// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Keyless]
public partial class CaseView
{
    public int CaseId { get; set; }

    public Guid Guid { get; set; }

    public bool IsActive { get; set; }

    public int ClientId { get; set; }

    [Required]
    [StringLength(100)]
    public string ClientName { get; set; }

    public int TypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    public int StatusId { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(150)]
    public string Title { get; set; }

    public string Summary { get; set; }
}