// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("CaseDocument")]
public partial class CaseDocument
{
    [Key]
    public int CaseDocumentId { get; set; }

    public Guid CaseDocumentGuid { get; set; }

    public bool CaseDocumentIsDeleted { get; set; }

    public int CaseDocumentCaseId { get; set; }

    public int CaseDocumentTypeId { get; set; }

    [StringLength(255)]
    public string CaseDocumentTitle { get; set; }

    [StringLength(500)]
    public string CaseDocumentSummary { get; set; }

    [StringLength(255)]
    public string CaseDocumentOriginalFileName { get; set; }

    [InverseProperty("CaseDocumentAuditCaseDocument")]
    public virtual ICollection<CaseDocumentAudit> CaseDocumentAudits { get; set; } = new List<CaseDocumentAudit>();

    [ForeignKey("CaseDocumentCaseId")]
    [InverseProperty("CaseDocuments")]
    public virtual Case CaseDocumentCase { get; set; }
}