// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("CaseUserAudit")]
public partial class CaseUserAudit
{
    [Key]
    public int CaseUserAuditId { get; set; }

    public int CaseUserAuditActionId { get; set; }

    public int CaseUserAuditCaseUserId { get; set; }

    public int CaseUserAuditUserId { get; set; }

    public DateTime CaseUserAuditDate { get; set; }

    [Required]
    public string CaseUserAuditBeforeJson { get; set; }

    [Required]
    public string CaseUserAuditAfterJson { get; set; }

    [Required]
    public string CaseUserAuditAffectedColumns { get; set; }

    [ForeignKey("CaseUserAuditActionId")]
    [InverseProperty("CaseUserAudits")]
    public virtual DataDictionary CaseUserAuditAction { get; set; }

    [ForeignKey("CaseUserAuditCaseUserId")]
    [InverseProperty("CaseUserAudits")]
    public virtual CaseUser CaseUserAuditCaseUser { get; set; }

    [ForeignKey("CaseUserAuditUserId")]
    [InverseProperty("CaseUserAudits")]
    public virtual User CaseUserAuditUser { get; set; }
}