// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("CaseCommentAudit")]
public partial class CaseCommentAudit
{
    [Key]
    public int CaseCommentAuditId { get; set; }

    public int CaseCommentAuditActionId { get; set; }

    public int CaseCommentAuditCaseCommentId { get; set; }

    public int CaseCommentAuditUserId { get; set; }

    public DateTime CaseCommentAuditDate { get; set; }

    [Required]
    public string CaseCommentAuditBeforeJson { get; set; }

    [Required]
    public string CaseCommentAuditAfterJson { get; set; }

    [Required]
    public string CaseCommentAuditAffectedColumns { get; set; }

    [ForeignKey("CaseCommentAuditActionId")]
    [InverseProperty("CaseCommentAudits")]
    public virtual DataDictionary CaseCommentAuditAction { get; set; }

    [ForeignKey("CaseCommentAuditCaseCommentId")]
    [InverseProperty("CaseCommentAudits")]
    public virtual CaseComment CaseCommentAuditCaseComment { get; set; }

    [ForeignKey("CaseCommentAuditUserId")]
    [InverseProperty("CaseCommentAudits")]
    public virtual User CaseCommentAuditUser { get; set; }
}