// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("CaseNoteAudit")]
public partial class CaseNoteAudit
{
    [Key]
    public int CaseNoteAuditId { get; set; }

    public int CaseNoteAuditActionId { get; set; }

    public int CaseNoteAuditCaseNoteId { get; set; }

    public int CaseNoteAuditUserId { get; set; }

    public DateTime CaseNoteAuditDate { get; set; }

    [Required]
    public string CaseNoteAuditBeforeJson { get; set; }

    [Required]
    public string CaseNoteAuditAfterJson { get; set; }

    [Required]
    public string CaseNoteAuditAffectedColumns { get; set; }

    [ForeignKey("CaseNoteAuditActionId")]
    [InverseProperty("CaseNoteAudits")]
    public virtual DataDictionary CaseNoteAuditAction { get; set; }

    [ForeignKey("CaseNoteAuditCaseNoteId")]
    [InverseProperty("CaseNoteAudits")]
    public virtual CaseNote CaseNoteAuditCaseNote { get; set; }

    [ForeignKey("CaseNoteAuditUserId")]
    [InverseProperty("CaseNoteAudits")]
    public virtual User CaseNoteAuditUser { get; set; }
}