// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("Case")]
[Index("CaseClientId", "CaseTitle", Name = "UQ_CaseTitle", IsUnique = true)]
public partial class Case
{
    [Key]
    public int CaseId { get; set; }

    public Guid CaseGuid { get; set; }

    public bool CaseIsActive { get; set; }

    public bool CaseIsDeleted { get; set; }

    public int CaseClientId { get; set; }

    public int CaseTypeId { get; set; }

    public int CaseStatusId { get; set; }

    [StringLength(150)]
    public string CaseTitle { get; set; }

    public string CaseSummary { get; set; }

    [InverseProperty("CaseAuditCase")]
    public virtual ICollection<CaseAudit> CaseAudits { get; set; } = new List<CaseAudit>();

    [ForeignKey("CaseClientId")]
    [InverseProperty("Cases")]
    public virtual Client CaseClient { get; set; }

    [InverseProperty("CaseCommentCase")]
    public virtual ICollection<CaseComment> CaseComments { get; set; } = new List<CaseComment>();

    [InverseProperty("CaseDocumentCase")]
    public virtual ICollection<CaseDocument> CaseDocuments { get; set; } = new List<CaseDocument>();

    [InverseProperty("CaseNoteCase")]
    public virtual ICollection<CaseNote> CaseNotes { get; set; } = new List<CaseNote>();

    [ForeignKey("CaseStatusId")]
    [InverseProperty("CaseCaseStatuses")]
    public virtual DataDictionary CaseStatus { get; set; }

    [ForeignKey("CaseTypeId")]
    [InverseProperty("CaseCaseTypes")]
    public virtual DataDictionary CaseType { get; set; }

    [InverseProperty("CaseUserCase")]
    public virtual ICollection<CaseUser> CaseUsers { get; set; } = new List<CaseUser>();
}