// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("CaseDocumentAudit")]
public partial class CaseDocumentAudit
{
    [Key]
    public int CaseDocumentAuditId { get; set; }

    public int CaseDocumentAuditActionId { get; set; }

    public int CaseDocumentAuditCaseDocumentId { get; set; }

    public int CaseDocumentAuditUserId { get; set; }

    public DateTime CaseDocumentAuditDate { get; set; }

    [Required]
    public string CaseDocumentAuditBeforeJson { get; set; }

    [Required]
    public string CaseDocumentAuditAfterJson { get; set; }

    [Required]
    public string CaseDocumentAuditAffectedColumns { get; set; }

    [ForeignKey("CaseDocumentAuditActionId")]
    [InverseProperty("CaseDocumentAudits")]
    public virtual DataDictionary CaseDocumentAuditAction { get; set; }

    [ForeignKey("CaseDocumentAuditCaseDocumentId")]
    [InverseProperty("CaseDocumentAudits")]
    public virtual CaseDocument CaseDocumentAuditCaseDocument { get; set; }

    [ForeignKey("CaseDocumentAuditUserId")]
    [InverseProperty("CaseDocumentAudits")]
    public virtual User CaseDocumentAuditUser { get; set; }
}