// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("Client")]
[Index("ClientName", Name = "UQ_ClientName", IsUnique = true)]
public partial class Client
{
    [Key]
    public int ClientId { get; set; }

    public Guid ClientGuid { get; set; }

    public bool ClientIsActive { get; set; }

    public bool ClientIsDeleted { get; set; }

    public int ClientTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string ClientName { get; set; }

    [StringLength(255)]
    public string ClientAddressLine1 { get; set; }

    [StringLength(255)]
    public string ClientAddressLine2 { get; set; }

    [StringLength(50)]
    public string ClientCity { get; set; }

    [StringLength(50)]
    public string ClientRegion { get; set; }

    [StringLength(10)]
    public string ClientPostalCode { get; set; }

    [StringLength(50)]
    public string ClientCountry { get; set; }

    [StringLength(20)]
    public string ClientPhoneNumber { get; set; }

    [StringLength(150)]
    public string ClientUrl { get; set; }

    [InverseProperty("CaseClient")]
    public virtual ICollection<Case> Cases { get; set; } = new List<Case>();

    [InverseProperty("ClientAuditClient")]
    public virtual ICollection<ClientAudit> ClientAudits { get; set; } = new List<ClientAudit>();

    [ForeignKey("ClientTypeId")]
    [InverseProperty("Clients")]
    public virtual DataDictionary ClientType { get; set; }

    [InverseProperty("ContractClient")]
    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();
}