// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractDocument")]
public partial class ContractDocument
{
    [Key]
    public int ContractDocumentId { get; set; }

    public Guid ContractDocumentGuid { get; set; }

    public bool ContractDocumentIsDeleted { get; set; }

    public int ContractDocumentContractId { get; set; }

    public int ContractDocumentTypeId { get; set; }

    [StringLength(255)]
    public string ContractDocumentTitle { get; set; }

    [StringLength(500)]
    public string ContractDocumentSummary { get; set; }

    [StringLength(255)]
    public string ContractDocumentOriginalFileName { get; set; }

    [InverseProperty("ContractDocumentAuditContractDocument")]
    public virtual ICollection<ContractDocumentAudit> ContractDocumentAudits { get; set; } = new List<ContractDocumentAudit>();

    [ForeignKey("ContractDocumentContractId")]
    [InverseProperty("ContractDocuments")]
    public virtual Contract ContractDocumentContract { get; set; }
}