// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractNote")]
public partial class ContractNote
{
    [Key]
    public int ContractNoteId { get; set; }

    public Guid ContractNoteGuid { get; set; }

    public bool ContractNoteIsDeleted { get; set; }

    public int ContractNoteContractId { get; set; }

    [StringLength(500)]
    public string ContractNoteBody { get; set; }

    [InverseProperty("ContractNoteAuditContractNote")]
    public virtual ICollection<ContractNoteAudit> ContractNoteAudits { get; set; } = new List<ContractNoteAudit>();

    [ForeignKey("ContractNoteContractId")]
    [InverseProperty("ContractNotes")]
    public virtual Contract ContractNoteContract { get; set; }
}