// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractUserAudit")]
public partial class ContractUserAudit
{
    [Key]
    public int ContractUserAuditId { get; set; }

    public int ContractUserAuditActionId { get; set; }

    public int ContractUserAuditContractUserId { get; set; }

    public int ContractUserAuditUserId { get; set; }

    public DateTime ContractUserAuditDate { get; set; }

    [Required]
    public string ContractUserAuditBeforeJson { get; set; }

    [Required]
    public string ContractUserAuditAfterJson { get; set; }

    [Required]
    public string ContractUserAuditAffectedColumns { get; set; }

    [ForeignKey("ContractUserAuditActionId")]
    [InverseProperty("ContractUserAudits")]
    public virtual DataDictionary ContractUserAuditAction { get; set; }

    [ForeignKey("ContractUserAuditContractUserId")]
    [InverseProperty("ContractUserAudits")]
    public virtual ContractUser ContractUserAuditContractUser { get; set; }

    [ForeignKey("ContractUserAuditUserId")]
    [InverseProperty("ContractUserAudits")]
    public virtual User ContractUserAuditUser { get; set; }
}