// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractAudit")]
public partial class ContractAudit
{
    [Key]
    public int ContractAuditId { get; set; }

    public int ContractAuditActionId { get; set; }

    public int ContractAuditContractId { get; set; }

    public int ContractAuditUserId { get; set; }

    public DateTime ContractAuditDate { get; set; }

    [Required]
    public string ContractAuditBeforeJson { get; set; }

    [Required]
    public string ContractAuditAfterJson { get; set; }

    [Required]
    public string ContractAuditAffectedColumns { get; set; }

    [ForeignKey("ContractAuditActionId")]
    [InverseProperty("ContractAudits")]
    public virtual DataDictionary ContractAuditAction { get; set; }

    [ForeignKey("ContractAuditContractId")]
    [InverseProperty("ContractAudits")]
    public virtual Contract ContractAuditContract { get; set; }

    [ForeignKey("ContractAuditUserId")]
    [InverseProperty("ContractAudits")]
    public virtual User ContractAuditUser { get; set; }
}