// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractCommentAudit")]
public partial class ContractCommentAudit
{
    [Key]
    public int ContractCommentAuditId { get; set; }

    public int ContractCommentAuditActionId { get; set; }

    public int ContractCommentAuditContractCommentId { get; set; }

    public int ContractCommentAuditUserId { get; set; }

    public DateTime ContractCommentAuditDate { get; set; }

    [Required]
    public string ContractCommentAuditBeforeJson { get; set; }

    [Required]
    public string ContractCommentAuditAfterJson { get; set; }

    [Required]
    public string ContractCommentAuditAffectedColumns { get; set; }

    [ForeignKey("ContractCommentAuditActionId")]
    [InverseProperty("ContractCommentAudits")]
    public virtual DataDictionary ContractCommentAuditAction { get; set; }

    [ForeignKey("ContractCommentAuditContractCommentId")]
    [InverseProperty("ContractCommentAudits")]
    public virtual ContractComment ContractCommentAuditContractComment { get; set; }

    [ForeignKey("ContractCommentAuditUserId")]
    [InverseProperty("ContractCommentAudits")]
    public virtual User ContractCommentAuditUser { get; set; }
}