// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Keyless]
public partial class ContractUserView
{
    public int ContractUserId { get; set; }

    public int ContractId { get; set; }

    public int UserId { get; set; }

    [StringLength(150)]
    public string ContractTitle { get; set; }

    [Required]
    [StringLength(100)]
    public string UserEmailAddress { get; set; }
}