// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Keyless]
public partial class ContractCommentView
{
    public int ContractCommentId { get; set; }

    public Guid ContractCommentGuid { get; set; }

    public int ContractId { get; set; }

    [StringLength(150)]
    public string ContractTitle { get; set; }

    [StringLength(500)]
    public string Comment { get; set; }
}