// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractNoteAudit")]
public partial class ContractNoteAudit
{
    [Key]
    public int ContractNoteAuditId { get; set; }

    public int ContractNoteAuditActionId { get; set; }

    public int ContractNoteAuditContractNoteId { get; set; }

    public int ContractNoteAuditUserId { get; set; }

    public DateTime ContractNoteAuditDate { get; set; }

    [Required]
    public string ContractNoteAuditBeforeJson { get; set; }

    [Required]
    public string ContractNoteAuditAfterJson { get; set; }

    [Required]
    public string ContractNoteAuditAffectedColumns { get; set; }

    [ForeignKey("ContractNoteAuditActionId")]
    [InverseProperty("ContractNoteAudits")]
    public virtual DataDictionary ContractNoteAuditAction { get; set; }

    [ForeignKey("ContractNoteAuditContractNoteId")]
    [InverseProperty("ContractNoteAudits")]
    public virtual ContractNote ContractNoteAuditContractNote { get; set; }

    [ForeignKey("ContractNoteAuditUserId")]
    [InverseProperty("ContractNoteAudits")]
    public virtual User ContractNoteAuditUser { get; set; }
}