// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("Contract")]
[Index("ContractClientId", "ContractTitle", Name = "UQ_ContractTitle", IsUnique = true)]
public partial class Contract
{
    [Key]
    public int ContractId { get; set; }

    public Guid ContractGuid { get; set; }

    public bool ContractIsActive { get; set; }

    public bool ContractIsDeleted { get; set; }

    public int ContractClientId { get; set; }

    public int ContractTypeId { get; set; }

    public int ContractStatusId { get; set; }

    [StringLength(150)]
    public string ContractTitle { get; set; }

    public string ContractSummary { get; set; }

    [InverseProperty("ContractAuditContract")]
    public virtual ICollection<ContractAudit> ContractAudits { get; set; } = new List<ContractAudit>();

    [ForeignKey("ContractClientId")]
    [InverseProperty("Contracts")]
    public virtual Client ContractClient { get; set; }

    [InverseProperty("ContractCommentContract")]
    public virtual ICollection<ContractComment> ContractComments { get; set; } = new List<ContractComment>();

    [InverseProperty("ContractDocumentContract")]
    public virtual ICollection<ContractDocument> ContractDocuments { get; set; } = new List<ContractDocument>();

    [InverseProperty("ContractNoteContract")]
    public virtual ICollection<ContractNote> ContractNotes { get; set; } = new List<ContractNote>();

    [ForeignKey("ContractStatusId")]
    [InverseProperty("ContractContractStatuses")]
    public virtual DataDictionary ContractStatus { get; set; }

    [ForeignKey("ContractTypeId")]
    [InverseProperty("ContractContractTypes")]
    public virtual DataDictionary ContractType { get; set; }

    [InverseProperty("ContractUserContract")]
    public virtual ICollection<ContractUser> ContractUsers { get; set; } = new List<ContractUser>();
}