// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractUser")]
[Index("ContractUserContractId", "ContractUserUserId", Name = "UQ_ContractUser", IsUnique = true)]
public partial class ContractUser
{
    [Key]
    public int ContractUserId { get; set; }

    public int ContractUserContractId { get; set; }

    public int ContractUserUserId { get; set; }

    public bool ContractUserIsDeleted { get; set; }

    [InverseProperty("ContractUserAuditContractUser")]
    public virtual ICollection<ContractUserAudit> ContractUserAudits { get; set; } = new List<ContractUserAudit>();

    [ForeignKey("ContractUserContractId")]
    [InverseProperty("ContractUsers")]
    public virtual Contract ContractUserContract { get; set; }

    [ForeignKey("ContractUserUserId")]
    [InverseProperty("ContractUsers")]
    public virtual User ContractUserUser { get; set; }
}