// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractDocumentAudit")]
public partial class ContractDocumentAudit
{
    [Key]
    public int ContractDocumentAuditId { get; set; }

    public int ContractDocumentAuditActionId { get; set; }

    public int ContractDocumentAuditContractDocumentId { get; set; }

    public int ContractDocumentAuditUserId { get; set; }

    public DateTime ContractDocumentAuditDate { get; set; }

    [Required]
    public string ContractDocumentAuditBeforeJson { get; set; }

    [Required]
    public string ContractDocumentAuditAfterJson { get; set; }

    [Required]
    public string ContractDocumentAuditAffectedColumns { get; set; }

    [ForeignKey("ContractDocumentAuditActionId")]
    [InverseProperty("ContractDocumentAudits")]
    public virtual DataDictionary ContractDocumentAuditAction { get; set; }

    [ForeignKey("ContractDocumentAuditContractDocumentId")]
    [InverseProperty("ContractDocumentAudits")]
    public virtual ContractDocument ContractDocumentAuditContractDocument { get; set; }

    [ForeignKey("ContractDocumentAuditUserId")]
    [InverseProperty("ContractDocumentAudits")]
    public virtual User ContractDocumentAuditUser { get; set; }
}