// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("ContractComment")]
public partial class ContractComment
{
    [Key]
    public int ContractCommentId { get; set; }

    public Guid ContractCommentGuid { get; set; }

    public bool ContractCommentIsDeleted { get; set; }

    public int ContractCommentContractId { get; set; }

    [StringLength(500)]
    public string ContractCommentBody { get; set; }

    [InverseProperty("ContractCommentAuditContractComment")]
    public virtual ICollection<ContractCommentAudit> ContractCommentAudits { get; set; } = new List<ContractCommentAudit>();

    [ForeignKey("ContractCommentContractId")]
    [InverseProperty("ContractComments")]
    public virtual Contract ContractCommentContract { get; set; }
}