// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("DataDictionary")]
[Index("DataDictionaryKey", Name = "UQ_DataDictionaryKey", IsUnique = true)]
public partial class DataDictionary
{
    [Key]
    public int DataDictionaryId { get; set; }

    public bool DataDictionaryIsActive { get; set; }

    public bool DataDictionaryIsDeleted { get; set; }

    public int DataDictionaryGroupId { get; set; }

    [Required]
    [StringLength(50)]
    public string DataDictionaryKey { get; set; }

    public int DataDictionaryValue { get; set; }

    [StringLength(150)]
    public string DataDictionaryDescription { get; set; }

    [InverseProperty("CaseAuditAction")]
    public virtual ICollection<CaseAudit> CaseAudits { get; set; } = new List<CaseAudit>();

    [InverseProperty("CaseStatus")]
    public virtual ICollection<Case> CaseCaseStatuses { get; set; } = new List<Case>();

    [InverseProperty("CaseType")]
    public virtual ICollection<Case> CaseCaseTypes { get; set; } = new List<Case>();

    [InverseProperty("CaseCommentAuditAction")]
    public virtual ICollection<CaseCommentAudit> CaseCommentAudits { get; set; } = new List<CaseCommentAudit>();

    [InverseProperty("CaseDocumentAuditAction")]
    public virtual ICollection<CaseDocumentAudit> CaseDocumentAudits { get; set; } = new List<CaseDocumentAudit>();

    [InverseProperty("CaseNoteAuditAction")]
    public virtual ICollection<CaseNoteAudit> CaseNoteAudits { get; set; } = new List<CaseNoteAudit>();

    [InverseProperty("CaseUserAuditAction")]
    public virtual ICollection<CaseUserAudit> CaseUserAudits { get; set; } = new List<CaseUserAudit>();

    [InverseProperty("ClientAuditAction")]
    public virtual ICollection<ClientAudit> ClientAudits { get; set; } = new List<ClientAudit>();

    [InverseProperty("ClientType")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    [InverseProperty("DataDictionaryAuditAction")]
    public virtual ICollection<DataDictionaryAudit> DataDictionaryAuditDataDictionaryAuditActions { get; set; } = new List<DataDictionaryAudit>();

    [InverseProperty("DataDictionaryAuditDataDictionary")]
    public virtual ICollection<DataDictionaryAudit> DataDictionaryAuditDataDictionaryAuditDataDictionaries { get; set; } = new List<DataDictionaryAudit>();

    [ForeignKey("DataDictionaryGroupId")]
    [InverseProperty("DataDictionaries")]
    public virtual DataDictionaryGroup DataDictionaryGroup { get; set; }

    [InverseProperty("DataDictionaryGroupAuditAction")]
    public virtual ICollection<DataDictionaryGroupAudit> DataDictionaryGroupAudits { get; set; } = new List<DataDictionaryGroupAudit>();

    [InverseProperty("UserAccountAuditAction")]
    public virtual ICollection<UserAccountAudit> UserAccountAudits { get; set; } = new List<UserAccountAudit>();

    [InverseProperty("UserAuditAction")]
    public virtual ICollection<UserAudit> UserAudits { get; set; } = new List<UserAudit>();

    [InverseProperty("UserType")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}