// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("DataDictionary")]
[Index("DataDictionaryGroupId", "DataDictionaryKey", Name = "UQ_DataDictionaryKey", IsUnique = true)]
public partial class DataDictionary
{
    [Key]
    public int DataDictionaryId { get; set; }

    public bool DataDictionaryIsActive { get; set; }

    public bool DataDictionaryIsDeleted { get; set; }

    public int DataDictionaryGroupId { get; set; }

    [Required]
    [StringLength(50)]
    public string DataDictionaryKey { get; set; }

    public int DataDictionaryValue { get; set; }

    [StringLength(150)]
    public string DataDictionaryDescription { get; set; }

    [InverseProperty("CaseAuditAction")]
    public virtual ICollection<CaseAudit> CaseAudits { get; set; } = new List<CaseAudit>();

    [InverseProperty("CaseStatus")]
    public virtual ICollection<Case> CaseCaseStatuses { get; set; } = new List<Case>();

    [InverseProperty("CaseType")]
    public virtual ICollection<Case> CaseCaseTypes { get; set; } = new List<Case>();

    [InverseProperty("CaseCommentAuditAction")]
    public virtual ICollection<CaseCommentAudit> CaseCommentAudits { get; set; } = new List<CaseCommentAudit>();

    [InverseProperty("CaseDocumentAuditAction")]
    public virtual ICollection<CaseDocumentAudit> CaseDocumentAudits { get; set; } = new List<CaseDocumentAudit>();

    [InverseProperty("CaseNoteAuditAction")]
    public virtual ICollection<CaseNoteAudit> CaseNoteAudits { get; set; } = new List<CaseNoteAudit>();

    [InverseProperty("CaseUserAuditAction")]
    public virtual ICollection<CaseUserAudit> CaseUserAudits { get; set; } = new List<CaseUserAudit>();

    [InverseProperty("ClientAuditAction")]
    public virtual ICollection<ClientAudit> ClientAudits { get; set; } = new List<ClientAudit>();

    [InverseProperty("ClientType")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    [InverseProperty("ContractAuditAction")]
    public virtual ICollection<ContractAudit> ContractAudits { get; set; } = new List<ContractAudit>();

    [InverseProperty("ContractCommentAuditAction")]
    public virtual ICollection<ContractCommentAudit> ContractCommentAudits { get; set; } = new List<ContractCommentAudit>();

    [InverseProperty("ContractStatus")]
    public virtual ICollection<Contract> ContractContractStatuses { get; set; } = new List<Contract>();

    [InverseProperty("ContractType")]
    public virtual ICollection<Contract> ContractContractTypes { get; set; } = new List<Contract>();

    [InverseProperty("ContractDocumentAuditAction")]
    public virtual ICollection<ContractDocumentAudit> ContractDocumentAudits { get; set; } = new List<ContractDocumentAudit>();

    [InverseProperty("ContractNoteAuditAction")]
    public virtual ICollection<ContractNoteAudit> ContractNoteAudits { get; set; } = new List<ContractNoteAudit>();

    [InverseProperty("ContractUserAuditAction")]
    public virtual ICollection<ContractUserAudit> ContractUserAudits { get; set; } = new List<ContractUserAudit>();

    [InverseProperty("DataDictionaryAuditAction")]
    public virtual ICollection<DataDictionaryAudit> DataDictionaryAuditDataDictionaryAuditActions { get; set; } = new List<DataDictionaryAudit>();

    [InverseProperty("DataDictionaryAuditDataDictionary")]
    public virtual ICollection<DataDictionaryAudit> DataDictionaryAuditDataDictionaryAuditDataDictionaries { get; set; } = new List<DataDictionaryAudit>();

    [ForeignKey("DataDictionaryGroupId")]
    [InverseProperty("DataDictionaries")]
    public virtual DataDictionaryGroup DataDictionaryGroup { get; set; }

    [InverseProperty("DataDictionaryGroupAuditAction")]
    public virtual ICollection<DataDictionaryGroupAudit> DataDictionaryGroupAudits { get; set; } = new List<DataDictionaryGroupAudit>();

    [InverseProperty("UserAccountAuditAction")]
    public virtual ICollection<UserAccountAudit> UserAccountAudits { get; set; } = new List<UserAccountAudit>();

    [InverseProperty("UserAuditAction")]
    public virtual ICollection<UserAudit> UserAudits { get; set; } = new List<UserAudit>();

    [InverseProperty("UserType")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();

    [InverseProperty("VendorAuditAction")]
    public virtual ICollection<VendorAudit> VendorAudits { get; set; } = new List<VendorAudit>();

    [InverseProperty("VendorCommentAuditAction")]
    public virtual ICollection<VendorCommentAudit> VendorCommentAudits { get; set; } = new List<VendorCommentAudit>();

    [InverseProperty("VendorDocumentAuditAction")]
    public virtual ICollection<VendorDocumentAudit> VendorDocumentAudits { get; set; } = new List<VendorDocumentAudit>();

    [InverseProperty("VendorNoteAuditAction")]
    public virtual ICollection<VendorNoteAudit> VendorNoteAudits { get; set; } = new List<VendorNoteAudit>();

    [InverseProperty("VendorUserAuditAction")]
    public virtual ICollection<VendorUserAudit> VendorUserAudits { get; set; } = new List<VendorUserAudit>();

    [InverseProperty("VendorStatus")]
    public virtual ICollection<Vendor> VendorVendorStatuses { get; set; } = new List<Vendor>();

    [InverseProperty("VendorType")]
    public virtual ICollection<Vendor> VendorVendorTypes { get; set; } = new List<Vendor>();
}