// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

public partial class LCMSDatabaseContext : DbContext
{
    public LCMSDatabaseContext(DbContextOptions<LCMSDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Case> Cases { get; set; }

    public virtual DbSet<CaseAudit> CaseAudits { get; set; }

    public virtual DbSet<CaseAuditView> CaseAuditViews { get; set; }

    public virtual DbSet<CaseComment> CaseComments { get; set; }

    public virtual DbSet<CaseCommentAudit> CaseCommentAudits { get; set; }

    public virtual DbSet<CaseCommentView> CaseCommentViews { get; set; }

    public virtual DbSet<CaseDocument> CaseDocuments { get; set; }

    public virtual DbSet<CaseDocumentAudit> CaseDocumentAudits { get; set; }

    public virtual DbSet<CaseDocumentView> CaseDocumentViews { get; set; }

    public virtual DbSet<CaseNote> CaseNotes { get; set; }

    public virtual DbSet<CaseNoteAudit> CaseNoteAudits { get; set; }

    public virtual DbSet<CaseNoteView> CaseNoteViews { get; set; }

    public virtual DbSet<CaseUser> CaseUsers { get; set; }

    public virtual DbSet<CaseUserAudit> CaseUserAudits { get; set; }

    public virtual DbSet<CaseUserView> CaseUserViews { get; set; }

    public virtual DbSet<CaseView> CaseViews { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientAudit> ClientAudits { get; set; }

    public virtual DbSet<ClientAuditView> ClientAuditViews { get; set; }

    public virtual DbSet<ClientView> ClientViews { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<ContractAudit> ContractAudits { get; set; }

    public virtual DbSet<ContractAuditView> ContractAuditViews { get; set; }

    public virtual DbSet<ContractComment> ContractComments { get; set; }

    public virtual DbSet<ContractCommentAudit> ContractCommentAudits { get; set; }

    public virtual DbSet<ContractCommentView> ContractCommentViews { get; set; }

    public virtual DbSet<ContractDocument> ContractDocuments { get; set; }

    public virtual DbSet<ContractDocumentAudit> ContractDocumentAudits { get; set; }

    public virtual DbSet<ContractDocumentView> ContractDocumentViews { get; set; }

    public virtual DbSet<ContractNote> ContractNotes { get; set; }

    public virtual DbSet<ContractNoteAudit> ContractNoteAudits { get; set; }

    public virtual DbSet<ContractNoteView> ContractNoteViews { get; set; }

    public virtual DbSet<ContractUser> ContractUsers { get; set; }

    public virtual DbSet<ContractUserAudit> ContractUserAudits { get; set; }

    public virtual DbSet<ContractUserView> ContractUserViews { get; set; }

    public virtual DbSet<ContractView> ContractViews { get; set; }

    public virtual DbSet<DataDictionary> DataDictionaries { get; set; }

    public virtual DbSet<DataDictionaryAudit> DataDictionaryAudits { get; set; }

    public virtual DbSet<DataDictionaryAuditView> DataDictionaryAuditViews { get; set; }

    public virtual DbSet<DataDictionaryGroup> DataDictionaryGroups { get; set; }

    public virtual DbSet<DataDictionaryGroupAudit> DataDictionaryGroupAudits { get; set; }

    public virtual DbSet<DataDictionaryGroupAuditView> DataDictionaryGroupAuditViews { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    public virtual DbSet<UserAccountAudit> UserAccountAudits { get; set; }

    public virtual DbSet<UserAccountView> UserAccountViews { get; set; }

    public virtual DbSet<UserAudit> UserAudits { get; set; }

    public virtual DbSet<UserAuditView> UserAuditViews { get; set; }

    public virtual DbSet<UserView> UserViews { get; set; }

    public virtual DbSet<Vendor> Vendors { get; set; }

    public virtual DbSet<VendorAudit> VendorAudits { get; set; }

    public virtual DbSet<VendorAuditView> VendorAuditViews { get; set; }

    public virtual DbSet<VendorComment> VendorComments { get; set; }

    public virtual DbSet<VendorCommentAudit> VendorCommentAudits { get; set; }

    public virtual DbSet<VendorCommentView> VendorCommentViews { get; set; }

    public virtual DbSet<VendorDocument> VendorDocuments { get; set; }

    public virtual DbSet<VendorDocumentAudit> VendorDocumentAudits { get; set; }

    public virtual DbSet<VendorDocumentView> VendorDocumentViews { get; set; }

    public virtual DbSet<VendorNote> VendorNotes { get; set; }

    public virtual DbSet<VendorNoteAudit> VendorNoteAudits { get; set; }

    public virtual DbSet<VendorNoteView> VendorNoteViews { get; set; }

    public virtual DbSet<VendorUser> VendorUsers { get; set; }

    public virtual DbSet<VendorUserAudit> VendorUserAudits { get; set; }

    public virtual DbSet<VendorUserView> VendorUserViews { get; set; }

    public virtual DbSet<VendorView> VendorViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Case>(entity =>
        {
            entity.Property(e => e.CaseGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CaseClient).WithMany(p => p.Cases)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Case_Client");

            entity.HasOne(d => d.CaseStatus).WithMany(p => p.CaseCaseStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Case_DataDictionary_Status");

            entity.HasOne(d => d.CaseType).WithMany(p => p.CaseCaseTypes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Case_DataDictionary_Type");
        });

        modelBuilder.Entity<CaseAudit>(entity =>
        {
            entity.Property(e => e.CaseAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.CaseAuditAction).WithMany(p => p.CaseAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseAudit_DataDictionary");

            entity.HasOne(d => d.CaseAuditCase).WithMany(p => p.CaseAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseAudit_Case");

            entity.HasOne(d => d.CaseAuditUser).WithMany(p => p.CaseAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseAudit_User");
        });

        modelBuilder.Entity<CaseAuditView>(entity =>
        {
            entity.ToView("CaseAuditView");
        });

        modelBuilder.Entity<CaseComment>(entity =>
        {
            entity.Property(e => e.CaseCommentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CaseCommentCase).WithMany(p => p.CaseComments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseComment_Case");
        });

        modelBuilder.Entity<CaseCommentAudit>(entity =>
        {
            entity.Property(e => e.CaseCommentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.CaseCommentAuditAction).WithMany(p => p.CaseCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseCommentAudit_DataDictionary");

            entity.HasOne(d => d.CaseCommentAuditCaseComment).WithMany(p => p.CaseCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseCommentAudit_CaseComment");

            entity.HasOne(d => d.CaseCommentAuditUser).WithMany(p => p.CaseCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseCommentAudit_User");
        });

        modelBuilder.Entity<CaseCommentView>(entity =>
        {
            entity.ToView("CaseCommentView");
        });

        modelBuilder.Entity<CaseDocument>(entity =>
        {
            entity.Property(e => e.CaseDocumentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CaseDocumentCase).WithMany(p => p.CaseDocuments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseDocument_Case");
        });

        modelBuilder.Entity<CaseDocumentAudit>(entity =>
        {
            entity.Property(e => e.CaseDocumentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.CaseDocumentAuditAction).WithMany(p => p.CaseDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseDocumentAudit_DataDictionary");

            entity.HasOne(d => d.CaseDocumentAuditCaseDocument).WithMany(p => p.CaseDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseDocumentAudit_CaseDocument");

            entity.HasOne(d => d.CaseDocumentAuditUser).WithMany(p => p.CaseDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseDocumentAudit_User");
        });

        modelBuilder.Entity<CaseDocumentView>(entity =>
        {
            entity.ToView("CaseDocumentView");
        });

        modelBuilder.Entity<CaseNote>(entity =>
        {
            entity.Property(e => e.CaseNoteGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CaseNoteCase).WithMany(p => p.CaseNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseNote_Case");
        });

        modelBuilder.Entity<CaseNoteAudit>(entity =>
        {
            entity.Property(e => e.CaseNoteAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.CaseNoteAuditAction).WithMany(p => p.CaseNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseNoteAudit_DataDictionary");

            entity.HasOne(d => d.CaseNoteAuditCaseNote).WithMany(p => p.CaseNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseNoteAudit_CaseNote");

            entity.HasOne(d => d.CaseNoteAuditUser).WithMany(p => p.CaseNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseNoteAudit_User");
        });

        modelBuilder.Entity<CaseNoteView>(entity =>
        {
            entity.ToView("CaseNoteView");
        });

        modelBuilder.Entity<CaseUser>(entity =>
        {
            entity.HasOne(d => d.CaseUserCase).WithMany(p => p.CaseUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseUser_Case");

            entity.HasOne(d => d.CaseUserUser).WithMany(p => p.CaseUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseUser_User");
        });

        modelBuilder.Entity<CaseUserAudit>(entity =>
        {
            entity.Property(e => e.CaseUserAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.CaseUserAuditAction).WithMany(p => p.CaseUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseUserAudit_DataDictionary");

            entity.HasOne(d => d.CaseUserAuditCaseUser).WithMany(p => p.CaseUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseUserAudit_CaseUser");

            entity.HasOne(d => d.CaseUserAuditUser).WithMany(p => p.CaseUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CaseUserAudit_User");
        });

        modelBuilder.Entity<CaseUserView>(entity =>
        {
            entity.ToView("CaseUserView");
        });

        modelBuilder.Entity<CaseView>(entity =>
        {
            entity.ToView("CaseView");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.Property(e => e.ClientGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.ClientType).WithMany(p => p.Clients)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Client_DataDictionary");
        });

        modelBuilder.Entity<ClientAudit>(entity =>
        {
            entity.Property(e => e.ClientAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ClientAuditAction).WithMany(p => p.ClientAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClientAudit_DataDictionary");

            entity.HasOne(d => d.ClientAuditClient).WithMany(p => p.ClientAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClientAudit_Client");

            entity.HasOne(d => d.ClientAuditUser).WithMany(p => p.ClientAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClientAudit_User");
        });

        modelBuilder.Entity<ClientAuditView>(entity =>
        {
            entity.ToView("ClientAuditView");
        });

        modelBuilder.Entity<ClientView>(entity =>
        {
            entity.ToView("ClientView");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.Property(e => e.ContractGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.ContractClient).WithMany(p => p.Contracts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contract_Client");

            entity.HasOne(d => d.ContractStatus).WithMany(p => p.ContractContractStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contract_DataDictionary_Status");

            entity.HasOne(d => d.ContractType).WithMany(p => p.ContractContractTypes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contract_DataDictionary_Type");
        });

        modelBuilder.Entity<ContractAudit>(entity =>
        {
            entity.Property(e => e.ContractAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ContractAuditAction).WithMany(p => p.ContractAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAudit_DataDictionary");

            entity.HasOne(d => d.ContractAuditContract).WithMany(p => p.ContractAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAudit_Contract");

            entity.HasOne(d => d.ContractAuditUser).WithMany(p => p.ContractAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAudit_User");
        });

        modelBuilder.Entity<ContractAuditView>(entity =>
        {
            entity.ToView("ContractAuditView");
        });

        modelBuilder.Entity<ContractComment>(entity =>
        {
            entity.Property(e => e.ContractCommentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.ContractCommentContract).WithMany(p => p.ContractComments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractComment_Contract");
        });

        modelBuilder.Entity<ContractCommentAudit>(entity =>
        {
            entity.Property(e => e.ContractCommentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ContractCommentAuditAction).WithMany(p => p.ContractCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractCommentAudit_DataDictionary");

            entity.HasOne(d => d.ContractCommentAuditContractComment).WithMany(p => p.ContractCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractCommentAudit_ContractComment");

            entity.HasOne(d => d.ContractCommentAuditUser).WithMany(p => p.ContractCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractCommentAudit_User");
        });

        modelBuilder.Entity<ContractCommentView>(entity =>
        {
            entity.ToView("ContractCommentView");
        });

        modelBuilder.Entity<ContractDocument>(entity =>
        {
            entity.Property(e => e.ContractDocumentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.ContractDocumentContract).WithMany(p => p.ContractDocuments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractDocument_Contract");
        });

        modelBuilder.Entity<ContractDocumentAudit>(entity =>
        {
            entity.Property(e => e.ContractDocumentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ContractDocumentAuditAction).WithMany(p => p.ContractDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractDocumentAudit_DataDictionary");

            entity.HasOne(d => d.ContractDocumentAuditContractDocument).WithMany(p => p.ContractDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractDocumentAudit_ContractDocument");

            entity.HasOne(d => d.ContractDocumentAuditUser).WithMany(p => p.ContractDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractDocumentAudit_User");
        });

        modelBuilder.Entity<ContractDocumentView>(entity =>
        {
            entity.ToView("ContractDocumentView");
        });

        modelBuilder.Entity<ContractNote>(entity =>
        {
            entity.Property(e => e.ContractNoteGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.ContractNoteContract).WithMany(p => p.ContractNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractNote_Contract");
        });

        modelBuilder.Entity<ContractNoteAudit>(entity =>
        {
            entity.Property(e => e.ContractNoteAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ContractNoteAuditAction).WithMany(p => p.ContractNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractNoteAudit_DataDictionary");

            entity.HasOne(d => d.ContractNoteAuditContractNote).WithMany(p => p.ContractNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractNoteAudit_ContractNote");

            entity.HasOne(d => d.ContractNoteAuditUser).WithMany(p => p.ContractNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractNoteAudit_User");
        });

        modelBuilder.Entity<ContractNoteView>(entity =>
        {
            entity.ToView("ContractNoteView");
        });

        modelBuilder.Entity<ContractUser>(entity =>
        {
            entity.HasOne(d => d.ContractUserContract).WithMany(p => p.ContractUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractUser_Contract");

            entity.HasOne(d => d.ContractUserUser).WithMany(p => p.ContractUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractUser_User");
        });

        modelBuilder.Entity<ContractUserAudit>(entity =>
        {
            entity.Property(e => e.ContractUserAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.ContractUserAuditAction).WithMany(p => p.ContractUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractUserAudit_DataDictionary");

            entity.HasOne(d => d.ContractUserAuditContractUser).WithMany(p => p.ContractUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractUserAudit_ContractUser");

            entity.HasOne(d => d.ContractUserAuditUser).WithMany(p => p.ContractUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractUserAudit_User");
        });

        modelBuilder.Entity<ContractUserView>(entity =>
        {
            entity.ToView("ContractUserView");
        });

        modelBuilder.Entity<ContractView>(entity =>
        {
            entity.ToView("ContractView");
        });

        modelBuilder.Entity<DataDictionary>(entity =>
        {
            entity.HasOne(d => d.DataDictionaryGroup).WithMany(p => p.DataDictionaries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionary_DataDictionarGroup");
        });

        modelBuilder.Entity<DataDictionaryAudit>(entity =>
        {
            entity.Property(e => e.DataDictionaryAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.DataDictionaryAuditAction).WithMany(p => p.DataDictionaryAuditDataDictionaryAuditActions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryAudit_DataDictionary_ActionId");

            entity.HasOne(d => d.DataDictionaryAuditDataDictionary).WithMany(p => p.DataDictionaryAuditDataDictionaryAuditDataDictionaries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryAudit_DataDictionary_DataDictionaryId");

            entity.HasOne(d => d.DataDictionaryAuditUser).WithMany(p => p.DataDictionaryAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryAudit_User");
        });

        modelBuilder.Entity<DataDictionaryAuditView>(entity =>
        {
            entity.ToView("DataDictionaryAuditView");
        });

        modelBuilder.Entity<DataDictionaryGroupAudit>(entity =>
        {
            entity.Property(e => e.DataDictionaryGroupAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.DataDictionaryGroupAuditAction).WithMany(p => p.DataDictionaryGroupAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryGroupAudit_DataDictionary");

            entity.HasOne(d => d.DataDictionaryGroupAuditDataDictionaryGroup).WithMany(p => p.DataDictionaryGroupAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryGroupAudit_DataDictionaryGroup");

            entity.HasOne(d => d.DataDictionaryGroupAuditUser).WithMany(p => p.DataDictionaryGroupAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataDictionaryGroupAudit_User");
        });

        modelBuilder.Entity<DataDictionaryGroupAuditView>(entity =>
        {
            entity.ToView("DataDictionaryGroupAuditView");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.UserType).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_DataDictionary");

            entity.HasOne(d => d.UserUserAccount).WithMany(p => p.Users).HasConstraintName("FK_User_UserAccount");
        });

        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.Property(e => e.UserAccountGuid).HasDefaultValueSql("NEWID()");
            entity.Property(e => e.UserAccountPasswordAttemptCount).HasDefaultValue(-1);
        });

        modelBuilder.Entity<UserAccountAudit>(entity =>
        {
            entity.Property(e => e.UserAccountAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.UserAccountAuditAction).WithMany(p => p.UserAccountAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAccountAudit_DataDictionary");

            entity.HasOne(d => d.UserAccountAuditUserAccount).WithMany(p => p.UserAccountAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAccountAudit_UserAccount");

            entity.HasOne(d => d.UserAccountAuditUser).WithMany(p => p.UserAccountAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAccountAudit_User");
        });

        modelBuilder.Entity<UserAccountView>(entity =>
        {
            entity.ToView("UserAccountView");
        });

        modelBuilder.Entity<UserAudit>(entity =>
        {
            entity.Property(e => e.UserAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.UserAuditAction).WithMany(p => p.UserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAudit_DataDictionary");

            entity.HasOne(d => d.UserAuditUser).WithMany(p => p.UserAuditUserAuditUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAudit_User");

            entity.HasOne(d => d.UserAuditUserIdSourceNavigation).WithMany(p => p.UserAuditUserAuditUserIdSourceNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAudit_User_Source");
        });

        modelBuilder.Entity<UserAuditView>(entity =>
        {
            entity.ToView("UserAuditView");
        });

        modelBuilder.Entity<UserView>(entity =>
        {
            entity.ToView("UserView");
        });

        modelBuilder.Entity<Vendor>(entity =>
        {
            entity.Property(e => e.VendorGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.VendorStatus).WithMany(p => p.VendorVendorStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vendor_DataDictionary_Status");

            entity.HasOne(d => d.VendorType).WithMany(p => p.VendorVendorTypes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vendor_DataDictionary_Type");
        });

        modelBuilder.Entity<VendorAudit>(entity =>
        {
            entity.Property(e => e.VendorAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.VendorAuditAction).WithMany(p => p.VendorAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorAudit_DataDictionary");

            entity.HasOne(d => d.VendorAuditUser).WithMany(p => p.VendorAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorAudit_User");

            entity.HasOne(d => d.VendorAuditVendor).WithMany(p => p.VendorAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorAudit_Vendor");
        });

        modelBuilder.Entity<VendorAuditView>(entity =>
        {
            entity.ToView("VendorAuditView");
        });

        modelBuilder.Entity<VendorComment>(entity =>
        {
            entity.Property(e => e.VendorCommentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.VendorCommentVendor).WithMany(p => p.VendorComments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorComment_Vendor");
        });

        modelBuilder.Entity<VendorCommentAudit>(entity =>
        {
            entity.Property(e => e.VendorCommentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.VendorCommentAuditAction).WithMany(p => p.VendorCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorCommentAudit_DataDictionary");

            entity.HasOne(d => d.VendorCommentAuditUser).WithMany(p => p.VendorCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorCommentAudit_User");

            entity.HasOne(d => d.VendorCommentAuditVendorComment).WithMany(p => p.VendorCommentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorCommentAudit_VendorComment");
        });

        modelBuilder.Entity<VendorCommentView>(entity =>
        {
            entity.ToView("VendorCommentView");
        });

        modelBuilder.Entity<VendorDocument>(entity =>
        {
            entity.Property(e => e.VendorDocumentGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.VendorDocumentVendor).WithMany(p => p.VendorDocuments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorDocument_Vendor");
        });

        modelBuilder.Entity<VendorDocumentAudit>(entity =>
        {
            entity.Property(e => e.VendorDocumentAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.VendorDocumentAuditAction).WithMany(p => p.VendorDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorDocumentAudit_DataDictionary");

            entity.HasOne(d => d.VendorDocumentAuditUser).WithMany(p => p.VendorDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorDocumentAudit_User");

            entity.HasOne(d => d.VendorDocumentAuditVendorDocument).WithMany(p => p.VendorDocumentAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorDocumentAudit_VendorDocument");
        });

        modelBuilder.Entity<VendorDocumentView>(entity =>
        {
            entity.ToView("VendorDocumentView");
        });

        modelBuilder.Entity<VendorNote>(entity =>
        {
            entity.Property(e => e.VendorNoteGuid).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.VendorNoteVendor).WithMany(p => p.VendorNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorNote_Vendor");
        });

        modelBuilder.Entity<VendorNoteAudit>(entity =>
        {
            entity.Property(e => e.VendorNoteAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.VendorNoteAuditAction).WithMany(p => p.VendorNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorNoteAudit_DataDictionary");

            entity.HasOne(d => d.VendorNoteAuditUser).WithMany(p => p.VendorNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorNoteAudit_User");

            entity.HasOne(d => d.VendorNoteAuditVendorNote).WithMany(p => p.VendorNoteAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorNoteAudit_VendorNote");
        });

        modelBuilder.Entity<VendorNoteView>(entity =>
        {
            entity.ToView("VendorNoteView");
        });

        modelBuilder.Entity<VendorUser>(entity =>
        {
            entity.HasOne(d => d.VendorUserUser).WithMany(p => p.VendorUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorUser_User");

            entity.HasOne(d => d.VendorUserVendor).WithMany(p => p.VendorUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorUser_Vendor");
        });

        modelBuilder.Entity<VendorUserAudit>(entity =>
        {
            entity.Property(e => e.VendorUserAuditDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.VendorUserAuditAction).WithMany(p => p.VendorUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorUserAudit_DataDictionary");

            entity.HasOne(d => d.VendorUserAuditUser).WithMany(p => p.VendorUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorUserAudit_User");

            entity.HasOne(d => d.VendorUserAuditVendorUser).WithMany(p => p.VendorUserAudits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorUserAudit_VendorUser");
        });

        modelBuilder.Entity<VendorUserView>(entity =>
        {
            entity.ToView("VendorUserView");
        });

        modelBuilder.Entity<VendorView>(entity =>
        {
            entity.ToView("VendorView");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}