// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("User")]
[Index("UserEmailAddress", Name = "UQ_UserEmailAddress", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    public Guid UserGuid { get; set; }

    public bool UserIsActive { get; set; }

    public bool UserIsDeleted { get; set; }

    public int? UserUserAccountId { get; set; }

    public int UserTypeId { get; set; }

    [StringLength(50)]
    public string UserFirstName { get; set; }

    [StringLength(50)]
    public string UserMiddleName { get; set; }

    [StringLength(50)]
    public string UserLastName { get; set; }

    [Required]
    [StringLength(100)]
    public string UserEmailAddress { get; set; }

    [StringLength(255)]
    public string UserAddressLine1 { get; set; }

    [StringLength(255)]
    public string UserAddressLine2 { get; set; }

    [StringLength(50)]
    public string UserCity { get; set; }

    [StringLength(50)]
    public string UserRegion { get; set; }

    [StringLength(10)]
    public string UserPostalCode { get; set; }

    [StringLength(50)]
    public string UserCountry { get; set; }

    [StringLength(20)]
    public string UserPhoneNumber { get; set; }

    [InverseProperty("CaseAuditUser")]
    public virtual ICollection<CaseAudit> CaseAudits { get; set; } = new List<CaseAudit>();

    [InverseProperty("CaseCommentAuditUser")]
    public virtual ICollection<CaseCommentAudit> CaseCommentAudits { get; set; } = new List<CaseCommentAudit>();

    [InverseProperty("CaseDocumentAuditUser")]
    public virtual ICollection<CaseDocumentAudit> CaseDocumentAudits { get; set; } = new List<CaseDocumentAudit>();

    [InverseProperty("CaseNoteAuditUser")]
    public virtual ICollection<CaseNoteAudit> CaseNoteAudits { get; set; } = new List<CaseNoteAudit>();

    [InverseProperty("CaseUserAuditUser")]
    public virtual ICollection<CaseUserAudit> CaseUserAudits { get; set; } = new List<CaseUserAudit>();

    [InverseProperty("CaseUserUser")]
    public virtual ICollection<CaseUser> CaseUsers { get; set; } = new List<CaseUser>();

    [InverseProperty("ClientAuditUser")]
    public virtual ICollection<ClientAudit> ClientAudits { get; set; } = new List<ClientAudit>();

    [InverseProperty("ContractAuditUser")]
    public virtual ICollection<ContractAudit> ContractAudits { get; set; } = new List<ContractAudit>();

    [InverseProperty("ContractCommentAuditUser")]
    public virtual ICollection<ContractCommentAudit> ContractCommentAudits { get; set; } = new List<ContractCommentAudit>();

    [InverseProperty("ContractDocumentAuditUser")]
    public virtual ICollection<ContractDocumentAudit> ContractDocumentAudits { get; set; } = new List<ContractDocumentAudit>();

    [InverseProperty("ContractNoteAuditUser")]
    public virtual ICollection<ContractNoteAudit> ContractNoteAudits { get; set; } = new List<ContractNoteAudit>();

    [InverseProperty("ContractUserAuditUser")]
    public virtual ICollection<ContractUserAudit> ContractUserAudits { get; set; } = new List<ContractUserAudit>();

    [InverseProperty("ContractUserUser")]
    public virtual ICollection<ContractUser> ContractUsers { get; set; } = new List<ContractUser>();

    [InverseProperty("DataDictionaryAuditUser")]
    public virtual ICollection<DataDictionaryAudit> DataDictionaryAudits { get; set; } = new List<DataDictionaryAudit>();

    [InverseProperty("DataDictionaryGroupAuditUser")]
    public virtual ICollection<DataDictionaryGroupAudit> DataDictionaryGroupAudits { get; set; } = new List<DataDictionaryGroupAudit>();

    [InverseProperty("UserAccountAuditUser")]
    public virtual ICollection<UserAccountAudit> UserAccountAudits { get; set; } = new List<UserAccountAudit>();

    [InverseProperty("UserAuditUserIdSourceNavigation")]
    public virtual ICollection<UserAudit> UserAuditUserAuditUserIdSourceNavigations { get; set; } = new List<UserAudit>();

    [InverseProperty("UserAuditUser")]
    public virtual ICollection<UserAudit> UserAuditUserAuditUsers { get; set; } = new List<UserAudit>();

    [ForeignKey("UserTypeId")]
    [InverseProperty("Users")]
    public virtual DataDictionary UserType { get; set; }

    [ForeignKey("UserUserAccountId")]
    [InverseProperty("Users")]
    public virtual UserAccount UserUserAccount { get; set; }

    [InverseProperty("VendorAuditUser")]
    public virtual ICollection<VendorAudit> VendorAudits { get; set; } = new List<VendorAudit>();

    [InverseProperty("VendorCommentAuditUser")]
    public virtual ICollection<VendorCommentAudit> VendorCommentAudits { get; set; } = new List<VendorCommentAudit>();

    [InverseProperty("VendorDocumentAuditUser")]
    public virtual ICollection<VendorDocumentAudit> VendorDocumentAudits { get; set; } = new List<VendorDocumentAudit>();

    [InverseProperty("VendorNoteAuditUser")]
    public virtual ICollection<VendorNoteAudit> VendorNoteAudits { get; set; } = new List<VendorNoteAudit>();

    [InverseProperty("VendorUserAuditUser")]
    public virtual ICollection<VendorUserAudit> VendorUserAudits { get; set; } = new List<VendorUserAudit>();

    [InverseProperty("VendorUserUser")]
    public virtual ICollection<VendorUser> VendorUsers { get; set; } = new List<VendorUser>();
}