// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("UserAccountAudit")]
public partial class UserAccountAudit
{
    [Key]
    public int UserAccountAuditId { get; set; }

    public int UserAccountAuditActionId { get; set; }

    public int UserAccountAuditUserAccountId { get; set; }

    public int UserAccountAuditUserId { get; set; }

    public DateTime UserAccountAuditDate { get; set; }

    [Required]
    public string UserAccountAuditBeforeJson { get; set; }

    [Required]
    public string UserAccountAuditAfterJson { get; set; }

    [Required]
    public string UserAccountAuditAffectedColumns { get; set; }

    [ForeignKey("UserAccountAuditActionId")]
    [InverseProperty("UserAccountAudits")]
    public virtual DataDictionary UserAccountAuditAction { get; set; }

    [ForeignKey("UserAccountAuditUserId")]
    [InverseProperty("UserAccountAudits")]
    public virtual User UserAccountAuditUser { get; set; }

    [ForeignKey("UserAccountAuditUserAccountId")]
    [InverseProperty("UserAccountAudits")]
    public virtual UserAccount UserAccountAuditUserAccount { get; set; }
}