// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("UserAccount")]
[Index("UserAccountUserName", Name = "UQ_UserAccountUserName", IsUnique = true)]
public partial class UserAccount
{
    [Key]
    public int UserAccountId { get; set; }

    public Guid UserAccountGuid { get; set; }

    public bool UserAccountIsActive { get; set; }

    public bool UserAccountIsDeleted { get; set; }

    [Required]
    [StringLength(50)]
    public string UserAccountUserName { get; set; }

    [Required]
    [StringLength(50)]
    public string UserAccountPassword { get; set; }

    [Required]
    [StringLength(255)]
    public string UserAccountPasswordHash { get; set; }

    public int UserAccountPasswordAttemptCount { get; set; }

    [InverseProperty("UserAccountAuditUserAccount")]
    public virtual ICollection<UserAccountAudit> UserAccountAudits { get; set; } = new List<UserAccountAudit>();

    [InverseProperty("UserUserAccount")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}