// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Keyless]
public partial class UserView
{
    public int UserId { get; set; }

    public Guid Guid { get; set; }

    public bool IsActive { get; set; }

    public int UserAccountId { get; set; }

    public bool UserAccountIsActive { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    public int TypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string MiddleName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    public string EmailAddress { get; set; }

    [StringLength(255)]
    public string AddressLine1 { get; set; }

    [StringLength(255)]
    public string AddressLine2 { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [StringLength(50)]
    public string Region { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }
}