// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorDocumentAudit")]
public partial class VendorDocumentAudit
{
    [Key]
    public int VendorDocumentAuditId { get; set; }

    public int VendorDocumentAuditActionId { get; set; }

    public int VendorDocumentAuditVendorDocumentId { get; set; }

    public int VendorDocumentAuditUserId { get; set; }

    public DateTime VendorDocumentAuditDate { get; set; }

    [Required]
    public string VendorDocumentAuditBeforeJson { get; set; }

    [Required]
    public string VendorDocumentAuditAfterJson { get; set; }

    [Required]
    public string VendorDocumentAuditAffectedColumns { get; set; }

    [ForeignKey("VendorDocumentAuditActionId")]
    [InverseProperty("VendorDocumentAudits")]
    public virtual DataDictionary VendorDocumentAuditAction { get; set; }

    [ForeignKey("VendorDocumentAuditUserId")]
    [InverseProperty("VendorDocumentAudits")]
    public virtual User VendorDocumentAuditUser { get; set; }

    [ForeignKey("VendorDocumentAuditVendorDocumentId")]
    [InverseProperty("VendorDocumentAudits")]
    public virtual VendorDocument VendorDocumentAuditVendorDocument { get; set; }
}