// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorCommentAudit")]
public partial class VendorCommentAudit
{
    [Key]
    public int VendorCommentAuditId { get; set; }

    public int VendorCommentAuditActionId { get; set; }

    public int VendorCommentAuditVendorCommentId { get; set; }

    public int VendorCommentAuditUserId { get; set; }

    public DateTime VendorCommentAuditDate { get; set; }

    [Required]
    public string VendorCommentAuditBeforeJson { get; set; }

    [Required]
    public string VendorCommentAuditAfterJson { get; set; }

    [Required]
    public string VendorCommentAuditAffectedColumns { get; set; }

    [ForeignKey("VendorCommentAuditActionId")]
    [InverseProperty("VendorCommentAudits")]
    public virtual DataDictionary VendorCommentAuditAction { get; set; }

    [ForeignKey("VendorCommentAuditUserId")]
    [InverseProperty("VendorCommentAudits")]
    public virtual User VendorCommentAuditUser { get; set; }

    [ForeignKey("VendorCommentAuditVendorCommentId")]
    [InverseProperty("VendorCommentAudits")]
    public virtual VendorComment VendorCommentAuditVendorComment { get; set; }
}