// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorNote")]
public partial class VendorNote
{
    [Key]
    public int VendorNoteId { get; set; }

    public Guid VendorNoteGuid { get; set; }

    public bool VendorNoteIsDeleted { get; set; }

    public int VendorNoteVendorId { get; set; }

    [StringLength(500)]
    public string VendorNoteBody { get; set; }

    [InverseProperty("VendorNoteAuditVendorNote")]
    public virtual ICollection<VendorNoteAudit> VendorNoteAudits { get; set; } = new List<VendorNoteAudit>();

    [ForeignKey("VendorNoteVendorId")]
    [InverseProperty("VendorNotes")]
    public virtual Vendor VendorNoteVendor { get; set; }
}