// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorNoteAudit")]
public partial class VendorNoteAudit
{
    [Key]
    public int VendorNoteAuditId { get; set; }

    public int VendorNoteAuditActionId { get; set; }

    public int VendorNoteAuditVendorNoteId { get; set; }

    public int VendorNoteAuditUserId { get; set; }

    public DateTime VendorNoteAuditDate { get; set; }

    [Required]
    public string VendorNoteAuditBeforeJson { get; set; }

    [Required]
    public string VendorNoteAuditAfterJson { get; set; }

    [Required]
    public string VendorNoteAuditAffectedColumns { get; set; }

    [ForeignKey("VendorNoteAuditActionId")]
    [InverseProperty("VendorNoteAudits")]
    public virtual DataDictionary VendorNoteAuditAction { get; set; }

    [ForeignKey("VendorNoteAuditUserId")]
    [InverseProperty("VendorNoteAudits")]
    public virtual User VendorNoteAuditUser { get; set; }

    [ForeignKey("VendorNoteAuditVendorNoteId")]
    [InverseProperty("VendorNoteAudits")]
    public virtual VendorNote VendorNoteAuditVendorNote { get; set; }
}