// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorComment")]
public partial class VendorComment
{
    [Key]
    public int VendorCommentId { get; set; }

    public Guid VendorCommentGuid { get; set; }

    public bool VendorCommentIsDeleted { get; set; }

    public int VendorCommentVendorId { get; set; }

    [StringLength(500)]
    public string VendorCommentBody { get; set; }

    [InverseProperty("VendorCommentAuditVendorComment")]
    public virtual ICollection<VendorCommentAudit> VendorCommentAudits { get; set; } = new List<VendorCommentAudit>();

    [ForeignKey("VendorCommentVendorId")]
    [InverseProperty("VendorComments")]
    public virtual Vendor VendorCommentVendor { get; set; }
}