// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Keyless]
public partial class VendorCommentView
{
    public int VendorCommentId { get; set; }

    public Guid VendorCommentGuid { get; set; }

    public int VendorId { get; set; }

    [Required]
    [StringLength(100)]
    public string VendorName { get; set; }

    [StringLength(500)]
    public string Comment { get; set; }
}