// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorDocument")]
public partial class VendorDocument
{
    [Key]
    public int VendorDocumentId { get; set; }

    public Guid VendorDocumentGuid { get; set; }

    public bool VendorDocumentIsDeleted { get; set; }

    public int VendorDocumentVendorId { get; set; }

    public int VendorDocumentTypeId { get; set; }

    [StringLength(255)]
    public string VendorDocumentTitle { get; set; }

    [StringLength(500)]
    public string VendorDocumentSummary { get; set; }

    [StringLength(255)]
    public string VendorDocumentOriginalFileName { get; set; }

    [InverseProperty("VendorDocumentAuditVendorDocument")]
    public virtual ICollection<VendorDocumentAudit> VendorDocumentAudits { get; set; } = new List<VendorDocumentAudit>();

    [ForeignKey("VendorDocumentVendorId")]
    [InverseProperty("VendorDocuments")]
    public virtual Vendor VendorDocumentVendor { get; set; }
}