// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorUser")]
[Index("VendorUserVendorId", "VendorUserUserId", Name = "UQ_VendorUser", IsUnique = true)]
public partial class VendorUser
{
    [Key]
    public int VendorUserId { get; set; }

    public int VendorUserVendorId { get; set; }

    public int VendorUserUserId { get; set; }

    public bool VendorUserIsDeleted { get; set; }

    [InverseProperty("VendorUserAuditVendorUser")]
    public virtual ICollection<VendorUserAudit> VendorUserAudits { get; set; } = new List<VendorUserAudit>();

    [ForeignKey("VendorUserUserId")]
    [InverseProperty("VendorUsers")]
    public virtual User VendorUserUser { get; set; }

    [ForeignKey("VendorUserVendorId")]
    [InverseProperty("VendorUsers")]
    public virtual Vendor VendorUserVendor { get; set; }
}