// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("Vendor")]
[Index("VendorName", Name = "UQ_VendorName", IsUnique = true)]
public partial class Vendor
{
    [Key]
    public int VendorId { get; set; }

    public Guid VendorGuid { get; set; }

    public bool VendorIsActive { get; set; }

    public bool VendorIsDeleted { get; set; }

    public int VendorTypeId { get; set; }

    public int VendorStatusId { get; set; }

    [Required]
    [StringLength(100)]
    public string VendorName { get; set; }

    [StringLength(255)]
    public string VendorAddressLine1 { get; set; }

    [StringLength(255)]
    public string VendorAddressLine2 { get; set; }

    [StringLength(50)]
    public string VendorCity { get; set; }

    [StringLength(50)]
    public string VendorRegion { get; set; }

    [StringLength(10)]
    public string VendorPostalCode { get; set; }

    [StringLength(50)]
    public string VendorCountry { get; set; }

    [StringLength(20)]
    public string VendorPhoneNumber { get; set; }

    [StringLength(150)]
    public string VendorUrl { get; set; }

    [InverseProperty("VendorAuditVendor")]
    public virtual ICollection<VendorAudit> VendorAudits { get; set; } = new List<VendorAudit>();

    [InverseProperty("VendorCommentVendor")]
    public virtual ICollection<VendorComment> VendorComments { get; set; } = new List<VendorComment>();

    [InverseProperty("VendorDocumentVendor")]
    public virtual ICollection<VendorDocument> VendorDocuments { get; set; } = new List<VendorDocument>();

    [InverseProperty("VendorNoteVendor")]
    public virtual ICollection<VendorNote> VendorNotes { get; set; } = new List<VendorNote>();

    [ForeignKey("VendorStatusId")]
    [InverseProperty("VendorVendorStatuses")]
    public virtual DataDictionary VendorStatus { get; set; }

    [ForeignKey("VendorTypeId")]
    [InverseProperty("VendorVendorTypes")]
    public virtual DataDictionary VendorType { get; set; }

    [InverseProperty("VendorUserVendor")]
    public virtual ICollection<VendorUser> VendorUsers { get; set; } = new List<VendorUser>();
}