// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorUserAudit")]
public partial class VendorUserAudit
{
    [Key]
    public int VendorUserAuditId { get; set; }

    public int VendorUserAuditActionId { get; set; }

    public int VendorUserAuditVendorUserId { get; set; }

    public int VendorUserAuditUserId { get; set; }

    public DateTime VendorUserAuditDate { get; set; }

    [Required]
    public string VendorUserAuditBeforeJson { get; set; }

    [Required]
    public string VendorUserAuditAfterJson { get; set; }

    [Required]
    public string VendorUserAuditAffectedColumns { get; set; }

    [ForeignKey("VendorUserAuditActionId")]
    [InverseProperty("VendorUserAudits")]
    public virtual DataDictionary VendorUserAuditAction { get; set; }

    [ForeignKey("VendorUserAuditUserId")]
    [InverseProperty("VendorUserAudits")]
    public virtual User VendorUserAuditUser { get; set; }

    [ForeignKey("VendorUserAuditVendorUserId")]
    [InverseProperty("VendorUserAudits")]
    public virtual VendorUser VendorUserAuditVendorUser { get; set; }
}