// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LCMS.Repository.Entities;

[Table("VendorAudit")]
public partial class VendorAudit
{
    [Key]
    public int VendorAuditId { get; set; }

    public int VendorAuditActionId { get; set; }

    public int VendorAuditVendorId { get; set; }

    public int VendorAuditUserId { get; set; }

    public DateTime VendorAuditDate { get; set; }

    [Required]
    public string VendorAuditBeforeJson { get; set; }

    [Required]
    public string VendorAuditAfterJson { get; set; }

    [Required]
    public string VendorAuditAffectedColumns { get; set; }

    [ForeignKey("VendorAuditActionId")]
    [InverseProperty("VendorAudits")]
    public virtual DataDictionary VendorAuditAction { get; set; }

    [ForeignKey("VendorAuditUserId")]
    [InverseProperty("VendorAudits")]
    public virtual User VendorAuditUser { get; set; }

    [ForeignKey("VendorAuditVendorId")]
    [InverseProperty("VendorAudits")]
    public virtual Vendor VendorAuditVendor { get; set; }
}